### PR TITLE
Update to react native 0.13.0+

### PR DESCRIPTION
**Pull request by BBB**
I've update the imports to match `react-native` `0.13.0` - `0.15.0-rc`.

### CODE REVIEW

**Comment by voronianski** [comment]
@BBB thanks, that's looks cool! Have you tested it with [ExampleApp](https://github.com/voronianski/react-native-effects-view/tree/master/example/EffectsApp)?

**Comment by BBB** [comment]
@voronianski great thanks! Can you do an npm release too?

**Comment by voronianski** [comment]
@BBB yep, in a sec

**Comment by voronianski** [comment]
@BBB done, new version - `0.2.0`

**Comment by BBB** [comment]
Great thanks!

**Pull request merged**
