### PR TITLE
update to RN >= 30

### PR DESCRIPTION
**Pull request by diegocstn**
I updated the js component with ES6 syntax and imports of React and ReactNative modules according to the changes of React system. I've also bumped up the version and updated the peerDependencies.

### CODE REVIEW

**Comment by diegocstn** [comment]
Could you please also publish the new version on npm?

**Comment by voronianski** [comment]
@dieguitoweb yes, in 1 hour

**Comment by diegocstn** [comment]
thanks ;)

**Comment by voronianski** [comment]
@dieguitoweb sorry for delay, done!

**Pull request merged**
